services:
  anaconda:
    build: "./.devcontainer"
    command: "sleep infinity"
    volumes:
      - .:/code:rw

  milvus:
    image: "milvusdb/milvus:v2.3.9"
    command: "milvus run standalone"
    security_opt:
      - seccomp:unconfined
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - ETCD_CONFIG_PATH=/milvus/configs/embedEtcd.yaml
      - COMMON_STORAGETYPE=local
    ports:
      - "19530:19530"
      - "9091:9091"
      - "2379:2379"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 90s
    volumes:
      - ./MilvusVolumes/milvus:/var/lib/milvus:rw
      - ./MilvusVolumes/embedEtcd.yaml:/milvus/configs/embedEtcd.yaml:rw